#!/usr/bin/env groovy
// pipeline docker image maven
pipeline {
    agent {
        docker {
            image 'maven:3.6.3-jdk-8'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }

    stages {
        stage('Test') {
            steps {
                echo 'test...'
            }
        }
    }

    stages {
        stage('Deploy') {
            steps {
                echo 'Deploy...'
            }
        }
    }
}


