#!/usr/bin/env groovy

pipeline {
    agent {
        docker {
            image 'gradle:jdk16'
            args '-u root'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'gradlew build'
            }
        }

        stage('Test') {
            steps {
                echo 'Test...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy...'
            }
        }
    }

}


