CREATE SCHEMA GLOBAL;

CREATE TABLE GLOBAL.GL00CLIE
(
    CO00CLIE SERIAL PRIMARY KEY,
    FANTCLIE VARCHAR(255) NOT NULL,
    BASECLIE VARCHAR(6)   NOT NULL,
    DOMICLIE VARCHAR(250) NOT NULL,
    STATCLIE INTEGER      NOT NULL,
    DTRECLIE TIMESTAMP
);

COMMENT ON TABLE GLOBAL.GL00CLIE IS 'TABELA PARA ARMAZENAR OS CLIENTES';
COMMENT ON COLUMN GLOBAL.GL00CLIE.CO00CLIE IS 'CÓDIGO DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.FANTCLIE IS 'NOME FANTASIA DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.BASECLIE IS 'REFERÊNCIA SCHEMA DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.DOMICLIE IS 'DOMÍNIO DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.STATCLIE IS 'STATUS DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.DTRECLIE IS 'DATA DO REGISTRO DO CLIENTE';

INSERT INTO GLOBAL.GL00CLIE (CO00CLIE, FANTCLIE, BASECLIE, DOMICLIE, STATCLIE, DTRECLIE)
VALUES (1, 'UNITURBO', 'cl0001', 'uniturbo', 1, CURRENT_DATE);

SELECT *
FROM GLOBAL.GL00CLIE;

CREATE SCHEMA CL0001;

CREATE TABLE CL0001.CL00USUA
(
    CO00USUA SERIAL PRIMARY KEY,
    NOMEUSUA VARCHAR(255) NOT NULL,
    FINAUSUA VARCHAR(255) NOT NULL,
    LANAUSUA VARCHAR(255) NOT NULL,
    GENEUSUA VARCHAR(1),
    MAILUSUA VARCHAR(255) NOT NULL,
    LOGIUSUA VARCHAR(50)  NOT NULL,
    PASSUSUA VARCHAR(255) NOT NULL,
    DTCRUSUA TIMESTAMP NOT NULL ,
    DTATUSUA TIMESTAMP
);


COMMENT ON TABLE CL0001.CL00USUA IS 'TABELA PARA ARMAZENAR OS USUÁRIOS';
COMMENT ON COLUMN CL0001.CL00USUA.CO00USUA IS 'CÓDIGO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.MAILUSUA IS 'EMAIL DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.NOMEUSUA IS 'NOME COMPLETO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.GENEUSUA IS 'GENERO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.FINAUSUA IS 'PRIMEIRO NOME DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.LANAUSUA IS 'SOBRENOME DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.LOGIUSUA IS 'LOGIN DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.PASSUSUA IS 'SENHA DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.DTCRUSUA IS 'DATA DE CRIAÇÃO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.DTATUSUA IS 'DATA DE ATUALIZAÇÃO USUÁRIO';

INSERT INTO CL0001.CL00USUA (CO00USUA, NOMEUSUA, FINAUSUA, LANAUSUA, GENEUSUA, MAILUSUA, LOGIUSUA, PASSUSUA, DTCRUSUA)
VALUES (1, 'Turbo Absoluto', 'Turbo', 'Absoluto', 'M', 'joaobrunw@gmail.com', 'turbo',
        '$2a$08$BwFSz4ev7FtHousFSwdSJe2IyaOYs5K5kkJm85nAwb0cxDqXvfx6C', CURRENT_DATE);

-- CREATE EXTENSION PGCRYPTO;

-- SELECT CRYPT('123456', GEN_SALT('bf', 8))

SELECT * FROM CL0001.CL00USUA
