CREATE SCHEMA GLOBAL;

CREATE TABLE GLOBAL.GL00CLIE
(
    CO00CLIE SERIAL PRIMARY KEY,
    FANTCLIE VARCHAR(255) NOT NULL,
    BASECLIE VARCHAR(10)  NOT NULL,
    DOMICLIE VARCHAR(250) NOT NULL,
    STATCLIE INTEGER      NOT NULL,
    DTRECLIE TIMESTAMP
);

COMMENT ON TABLE GLOBAL.GL00CLIE IS 'TABELA PARA ARMAZENAR OS CLIENTES';
COMMENT ON COLUMN GLOBAL.GL00CLIE.CO00CLIE IS 'CÓDIGO DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.FANTCLIE IS 'NOME FANTASIA DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.BASECLIE IS 'REFERÊNCIA SCHEMA DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.DOMICLIE IS 'DOMÍNIO DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.STATCLIE IS 'STATUS DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00CLIE.DTRECLIE IS 'DATA DO REGISTRO DO CLIENTE';

INSERT INTO GLOBAL.GL00CLIE (CO00CLIE, FANTCLIE, BASECLIE, DOMICLIE, STATCLIE, DTRECLIE)
VALUES (1, 'UNITURBO', 'cl0001', 'uniturbo', 1, CURRENT_DATE);

SELECT *
FROM GLOBAL.GL00CLIE;

CREATE SCHEMA CL0001;

CREATE TABLE CL0001.CL00USUA
(
    CO00USUA SERIAL PRIMARY KEY,
    NOMEUSUA VARCHAR(255) NOT NULL,
    GENEUSUA VARCHAR(1),
    MAILUSUA VARCHAR(255) NOT NULL,
    LOGIUSUA VARCHAR(50),
    PASSUSUA VARCHAR(255),
    DTCRUSUA TIMESTAMP    NOT NULL,
    DTATUSUA TIMESTAMP,
    BASEUSUA VARCHAR(6),
    DTNCUSUA DATE         NOT NULL,
    ATIVUSUA INT          NOT NULL
);


COMMENT ON TABLE CL0001.CL00USUA IS 'TABELA PARA ARMAZENAR OS USUÁRIOS';
COMMENT ON COLUMN CL0001.CL00USUA.CO00USUA IS 'CÓDIGO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.MAILUSUA IS 'EMAIL DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.NOMEUSUA IS 'NOME COMPLETO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.GENEUSUA IS 'GENERO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.DTNCUSUA IS 'DATA NASCIMENTO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.LOGIUSUA IS 'LOGIN DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.PASSUSUA IS 'SENHA DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.DTCRUSUA IS 'DATA DE CRIAÇÃO DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.DTATUSUA IS 'DATA DE ATUALIZAÇÃO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.BASEUSUA IS 'SCHEMA DO USUÁRIO';
COMMENT ON COLUMN CL0001.CL00USUA.ATIVUSUA IS 'STATUS DO USUÁRIO';
--
-- INSERT INTO CL0001.CL00USUA (CO00USUA, NOMEUSUA, GENEUSUA, MAILUSUA, LOGIUSUA, PASSUSUA, DTCRUSUA)
-- VALUES (1, 'Turbo Absoluto', 'M', 'joaobrunw@gmail.com', 'turbo',
--         '$2a$08$BwFSz4ev7FtHousFSwdSJe2IyaOYs5K5kkJm85nAwb0cxDqXvfx6C', CURRENT_DATE);

-- CREATE EXTENSION PGCRYPTO;

-- SELECT CRYPT('123456', GEN_SALT('bf', 8))

SELECT *
FROM CL0001.CL00USUA;



CREATE TABLE GLOBAL.GL00FILE
(
    CO90FILE VARCHAR(50)   NOT NULL PRIMARY KEY,
    PATHFILE VARCHAR(4000) NOT NULL,
    NOMEFILE VARCHAR(4000) NOT NULL,
    EXTEFILE VARCHAR(10)   NOT NULL,
    BASECLIE VARCHAR(10),
    DTCRFILE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SIZEFILE INTEGER
);
COMMENT ON TABLE GLOBAL.GL00FILE IS 'TABELA PARA ARMAZENAR OS ARQUIVOS';
COMMENT ON COLUMN GLOBAL.GL00FILE.CO00FILE IS 'CÓDIGO DO ARQUIVO';
COMMENT ON COLUMN GLOBAL.GL00FILE.PATHFILE IS 'CAMINHO DO ARQUIVO';
COMMENT ON COLUMN GLOBAL.GL00FILE.NOMEFILE IS 'NOME DO ARQUIVO';
COMMENT ON COLUMN GLOBAL.GL00FILE.EXTEFILE IS 'EXTENSÃO DO ARQUIVO';
COMMENT ON COLUMN GLOBAL.GL00FILE.BASECLIE IS 'BASE DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL00FILE.DTCRFILE IS 'DATA DE CRIAÇÃO DO ARQUIVO';
COMMENT ON COLUMN GLOBAL.GL00FILE.SIZEFILE IS 'TAMANHO DO ARQUIVO';



CREATE TABLE GLOBAL.GL00CONS
(
    CO00CONS SERIAL PRIMARY KEY,
    MAILCONS VARCHAR(255) NOT NULL,
    NOMECONS VARCHAR(255) NOT NULL,
    DTNCCONS DATE         NOT NULL,
    GENECONS VARCHAR      NOT NULL,
    CO00FILE VARCHAR(50),
    ATIVCONS NUMERIC(1)   NOT NULL
);


COMMENT ON TABLE GLOBAL.GL00CONS IS 'TABELA PARA ARMAZENAR OS CONSUMIDORES';
COMMENT ON COLUMN GLOBAL.GL00CONS.CO00FILE IS 'CÓDIGO DO CONSUMIDOR';
COMMENT ON COLUMN GLOBAL.GL00CONS.MAILCONS IS 'EMAIL DO CONSUMIDOR';
COMMENT ON COLUMN GLOBAL.GL00CONS.NOMECONS IS 'NOME DO CONSUMIDOR';
COMMENT ON COLUMN GLOBAL.GL00CONS.DTNCCONS IS 'DATA DE NASCIMENTO DO CONSUMIDOR';
COMMENT ON COLUMN GLOBAL.GL00CONS.GENECONS IS 'GENERO DO CONSUMIDOR';
COMMENT ON COLUMN GLOBAL.GL00CONS.CO00FILE IS 'FOTO DO CONSUMIDOR';
COMMENT ON COLUMN GLOBAL.GL00CONS.ATIVCONS IS 'STATUS DO CONSUMIDOR';


CREATE TABLE GLOBAL.GL01CLIE
(
    CO01CLIE SERIAL PRIMARY KEY,
    CO00CLIE INTEGER REFERENCES GLOBAL.GL00CLIE (CO00CLIE),
    EMNUCLIE TEXT,
    EMRUCLIE TEXT
);

COMMENT ON TABLE GLOBAL.GL01CLIE IS 'TABELA PARA ARMAZENAR OS PARAMETROS DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL01CLIE.CO00CLIE IS 'CÓDIGO DO PARAMETRO';
COMMENT ON COLUMN GLOBAL.GL01CLIE.CO00CLIE IS 'CÓDIGO DO CLIENTE';
COMMENT ON COLUMN GLOBAL.GL01CLIE.EMNUCLIE IS 'TEMPLATE EMAIL NOVO USUÁRIO';
COMMENT ON COLUMN GLOBAL.GL01CLIE.EMRUCLIE IS 'TEMPLATE EMAIL RESET SENHA USUÁRIO';


CREATE TABLE GLOBAL.GL00MAIL
(
    CO00MAIL SERIAL PRIMARY KEY,
    REFEMAIL VARCHAR(255),
    PARAMAIL TEXT      NOT NULL,
    CONTMAIL TEXT,
    ASUNMAIL TEXT,
    DTCRMAIL TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
    DTENMAIL TIMESTAMP,
    STATMAIL INT                DEFAULT 0
);

COMMENT ON TABLE GLOBAL.GL00MAIL IS 'TABELA PARA ARMAZENAR OS EMAILS';
COMMENT ON COLUMN GLOBAL.GL00MAIL.REFEMAIL IS 'CÓDIGO DO EMAIL';
COMMENT ON COLUMN GLOBAL.GL00MAIL.PARAMAIL IS 'RECEPTOR OU RECEPTORES DO EMAIL';
COMMENT ON COLUMN GLOBAL.GL00MAIL.CONTMAIL IS 'CONTEUDO DO EMAIL';
COMMENT ON COLUMN GLOBAL.GL00MAIL.ASUNMAIL IS 'ASSUNTO DO EMAIL';
COMMENT ON COLUMN GLOBAL.GL00MAIL.DTCRMAIL IS 'DATA CRIAÇAO DO EMAIL';
COMMENT ON COLUMN GLOBAL.GL00MAIL.DTENMAIL IS 'DATA ENVIO DO EMAIL';
